name: minimal_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: /Users/Jacob/Philes/DevFiles/FlutterFiles/FlutterProjects/LenovoSmartDisplay/minimal_clock/minimal_clock/flutter_clock_helper
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
